### ISSUE TITLE
REST-API-Documentation

### ISSUE THREAD

**Issue by aantakli** [dfki-asr/compass#14]
The base path in restapi-doc.html set as http://example.com/compass/restv1 is wrong, it should be http://example.com/compass/resources/restv1

**Comment by aantakli** [comment]
and maybe you could write http://(your-compass-path)/resources/restv1, thats more variable

**Comment by wherget** [comment]
For your first point: You're totally right, sorry about that. We'll get that fixed for the next release.

On the second point: I don't exactly see how that's better than the current state of affairs. Hopefully someone who's capable of running their own HTTP Requests against the REST interface can expend the mental effort to rewrite the example URL. Your input will be considered though.
Swagger actually has a means to generate the documentation completely on the fly (with correct API path and everything), but that needs a significant amount of effort we weren't willing to expend when we first introduced the Swagger Documentation feature. Maybe in a future release (as always, patches and pull requests welcome)...
