### ISSUE TITLE
REST-Module in Archetype

### ISSUE THREAD

**Issue by aantakli** [dfki-asr/compass#15]
Is there a possibility to extend the REST-API within the custom archetype, because there is no REST-Module

**Comment by wherget** [comment]
Yes, that's indeed possible.
If you started from the 1.0 archetype, you need to create the module yourself, and structure your dependencies similar to what core COMPASS does (i.e. have your Webapp Overlay depend on your REST module).
An example on how to do that has in fact already made it into the develop branch via #11. It will be included in the upcoming 2.0.0 release. Feel free to check out `develop` and generate a project using the (currently versioned) `1.1-SNAPSHOT` archetype, to see how it's supposed to work.
